version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: node index.js
